[project]
name = "agents-template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ace-tools>=0.0",
    "faker>=37.1.0",
    "fastexcel>=0.13.0",
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.6",
    "matplotlib>=3.10.1",
    "openpyxl>=3.1.5",
    "oracledb>=3.1.0",
    "pandas>=2.2.3",
    "pandas-profiling>=3.6.6",
    "plotly>=6.0.1",
    "polars>=1.27.1",
    "python-dotenv>=1.1.0",
    "seaborn>=0.13.2",
    "setuptools>=80.0.0",
    "smbprotocol>=1.15.0",
    "sqlalchemy>=2.0.40",
    "xlsxwriter>=3.2.2",
    "chainlit>=2.5.5",
    "duckduckgo-search>=8.0.1",
    "google-adk>=0.2.0",
    "litellm>=1.67.2",
    "openai-agents>=0.0.12",
    "pandas>=2.2.3",
    "pydantic>=2.11.3",
    "fastapi[standard]>=0.115.12",
    "langchain-nvidia-ai-endpoints>=0.3.10",
    "langchain>=0.3.25",
    "duckpy>=2.1.1",
    "groq>=0.26.0",
    "langchain-groq>=0.3.2",
    "langgraph>=0.4.8",
    "langchain-openai>=0.3.21",
]
